# Generated by Django 5.1.4 on 2025-01-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='popular_comment',
            field=models.BooleanField(default=False, verbose_name='آیا کامنت جز کامنت های محبوب باشه؟'),
        ),
    ]
