# Generated by Django 5.1.4 on 2025-01-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_comment_popular_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='popular_comment',
            field=models.BooleanField(default=False, verbose_name='آیا کامنت به کامنت های محبوب اضافه شود؟'),
        ),
    ]
