# Generated by Django 5.1.4 on 2025-01-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_options_alter_profile_created_at_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.AddField(
            model_name='user',
            name='about_me',
            field=models.CharField(default=1, max_length=250, verbose_name='درباره من'),
            preserve_default=False,
        ),
    ]
