# Generated by Django 5.1.4 on 2025-02-24 02:31

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0008_alter_comment_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=10000, verbose_name='قیمت کل')),
                ('is_status', models.BooleanField(default=False, verbose_name='آیا پرداخت شده یا نه؟')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ سفارش')),
                ('product_status', models.CharField(choices=[('processing', 'درحال پردازش'), ('shipped', 'ارسال شد'), ('delivered', 'تحویل داده شد')], default='processing', max_length=30, verbose_name='وضعیت محصول')),
                ('order_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', editable=False, length=10, max_length=10, prefix='', unique=True, verbose_name='شناسه سفارش')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(max_length=100, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=14, verbose_name='تلفن')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('zipcode', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='CartOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=10, verbose_name='شماره فاکتور')),
                ('product_status', models.CharField(choices=[('processing', 'درحال پردازش'), ('shipped', 'ارسال شد'), ('delivered', 'تحویل داده شد')], default='processing', max_length=30, verbose_name='وضعیت محصول')),
                ('qty', models.IntegerField(default=0, verbose_name='تعداد')),
                ('price', models.IntegerField(default=10000, verbose_name='قیمت')),
                ('total', models.IntegerField(default=100000, verbose_name='جمع کل')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cartorder', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'آیتم سفارش در سبد خرید',
                'verbose_name_plural': 'آیتم \u200cهای سفارش در سبد خرید',
            },
        ),
    ]
