# Generated by Django 5.1.4 on 2025-02-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='address',
            field=models.TextField(default=1, verbose_name='آدرس'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartorder',
            name='email',
            field=models.EmailField(default=1, max_length=100, verbose_name='ایمیل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartorder',
            name='first_name',
            field=models.CharField(default=1, max_length=50, verbose_name='نام'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartorder',
            name='last_name',
            field=models.CharField(default=1, max_length=50, verbose_name='نام خانوادگی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartorder',
            name='phone',
            field=models.CharField(default=1, max_length=14, verbose_name='تلفن'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartorder',
            name='zipcode',
            field=models.CharField(default=1, max_length=10, verbose_name='کد پستی'),
            preserve_default=False,
        ),
    ]
