# Generated by Django 5.1.4 on 2025-02-24 02:38

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='order_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=10, max_length=10, prefix='', unique=True, verbose_name='شناسه سفارش'),
        ),
    ]
