# Generated by Django 5.1.4 on 2025-02-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartorder_address_cartorder_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitem',
            name='invoice_no',
            field=models.CharField(max_length=10, verbose_name='شماره فاکتور'),
        ),
    ]
